# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dream Alliance
email: 1912544842@qq.com
description: The Main WebSite of Dream Alliance
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dreamalliance.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  DreamAlliance
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f29fbc8333e4d996b6d8     #生成的clientID
  clientSecret: 4e597a65bbee8e9ba63f1d1cfb45335e0a743df3   #生成的clientSecret
  repo: blog_issues    #仓库名称
  owner: DreamAlliance   #github用户名
  admin: DreamAlliance
  distractionFreeMode: true #是否启用类似FB的阴影遮罩