# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dream Alliance
email: 1912544842@qq.com
description: The Main WebSite of Dream Alliance
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dreamalliance.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  DreamAlliance
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown

# Gitalk settings
comment_gitalk_clientId: 'f29fbc8333e4d996b6d8'
comment_gitalk_clientSecret: 'c06976a4fdecc06fac887d39e919a76a9c1c9c3e'
comment_gitalk_repo: dreamalliance.github.io
github_username: DreamAlliance
