# Site settings
title: 梦想彼岸联盟
SEOTitle: 梦想彼岸联盟 | Dream Alliance
header-img: img/main/desk.jpg
email: 1912544842@qq.com
description: "GET UP AND RUNNING WITH Dream Alliance."
keyword: "Dream Alliance, Dream Alliance's Website, 梦想彼岸联盟的博客, Dream Alliance, 梦想彼岸联盟, Linux, ESP8266, ESP32"
url: "http://dreamalliance.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/DreamAlliance/dreamalliance.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "GET UP AND RUNNING WITH Dream Alliance."
sidebar-avatar: /img/main/da.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
#weibo_username:     知了个非
#zhihu_username:     takanashi_tsubasa
github_username:    DreamAlliance
#facebook_username:  
#jianshu_username:   
#twitter_username:   Zhifei_Pan




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: pamgaoshow

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 93f02e8c124dc0f6ad59     #生成的clientID
  clientSecret: 390d653c8769372df411dab3f8ff7719b6ae6b67   #生成的clientSecret
  repo: blog_issues    #仓库名称
  owner: DreamAlliance   #github用户名
  admin: Peter-Zhifei
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 

# Google Analytics
#ga_track_id: 'UA-175676693-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto                # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "梦程的小窝",
        href: "https://www.dreamcstudio.cn/"
    },{
        title: "Atai.啊泰",
        href: "https://icomgx.cn/"
    },{
        title: "胖鸡酱的杂货铺",
        href: "https://panzhifei.xyz/"
    }
]
